import '../models/models.dart';

class MockData {
  static List<ServiceProvider> providers = [
    ServiceProvider(
      id: 'prov_kamal',
      name: 'Kamal Perera',
      category: 'plumbing',
      rating: 4.8,
      reviewCount: 42,
      jobsCompleted: 212,
      onTimePercentage: 98,
      experienceYears: 6,
      startingPrice: 1200.0,
      distanceKm: 1.8,
      imageUrl: 'https://images.unsplash.com/photo-1540569014015-19a7be504e3a?w=400',
      about: 'Licensed master plumber with 6+ years of experience handling residential plumbing repairs, leak detection, drainage fixes, and tap replacements in the Colombo and Gampaha areas.',
      pastWorkImages: [
        'https://images.unsplash.com/photo-1585704032915-c3400ca199e7?w=400',
        'https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?w=400',
        'https://images.unsplash.com/photo-1504148455328-c376907d081c?w=400',
      ],
      pricingTable: [
        {'item': 'Tap replacement / repair', 'price': 1200.0, 'unit': 'per tap'},
        {'item': 'Pipe leak repair', 'price': 2500.0, 'unit': 'fixed quote'},
        {'item': 'Drainage unblocking', 'price': 3000.0, 'unit': 'standard'},
        {'item': 'Complete bathroom checkup', 'price': 4500.0, 'unit': 'full inspect'},
      ],
    ),
    ServiceProvider(
      id: 'prov_nadesha',
      name: 'Nadesha Silva',
      category: 'cleaning',
      rating: 4.9,
      reviewCount: 68,
      jobsCompleted: 340,
      onTimePercentage: 99,
      experienceYears: 4,
      startingPrice: 2000.0,
      distanceKm: 2.3,
      imageUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400',
      about: 'Professional home & deep cleaning specialist. Equipped with eco-friendly sanitizing tools, verified background check, and trusted by hundreds of homeowners.',
      pastWorkImages: [
        'https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=400',
        'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?w=400',
      ],
      pricingTable: [
        {'item': 'Deep Kitchen Cleaning', 'price': 3500.0, 'unit': 'standard'},
        {'item': 'Bathroom Sanitization', 'price': 2000.0, 'unit': 'per bath'},
        {'item': 'Full House Deep Clean', 'price': 8500.0, 'unit': '2-3 rooms'},
      ],
    ),
    ServiceProvider(
      id: 'prov_kasun',
      name: 'Kasun Wickramasinghe',
      category: 'carpentry',
      rating: 4.7,
      reviewCount: 31,
      jobsCompleted: 145,
      onTimePercentage: 95,
      experienceYears: 4,
      startingPrice: 1800.0,
      distanceKm: 3.5,
      imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
      about: 'Specialist in custom kitchen cabinets, bathroom vanities, wardrobe drawer repairs, and door lock adjustments. Clear upfront quotes and formal contracts before work begins.',
      pastWorkImages: [
        'https://images.unsplash.com/photo-1538688525198-9b88f6f53126?w=400',
        'https://images.unsplash.com/photo-1513694203232-719a280e022f?w=400',
      ],
      pricingTable: [
        {'item': 'Hinge / lock adjustment', 'price': 1800.0, 'unit': 'per door'},
        {'item': 'Drawer runner replacement', 'price': 2400.0, 'unit': 'per drawer'},
        {'item': 'Cabinet shelf installation', 'price': 4000.0, 'unit': 'per unit'},
      ],
    ),
    ServiceProvider(
      id: 'prov_sunil',
      name: 'Sunil Fernando',
      category: 'electrical',
      rating: 4.8,
      reviewCount: 54,
      jobsCompleted: 280,
      onTimePercentage: 97,
      experienceYears: 7,
      startingPrice: 1500.0,
      distanceKm: 1.2,
      imageUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400',
      about: 'Certified residential electrician. Emergency trip switch repairs, light fixture installations, rewiring diagnostics, and surge protection.',
      pastWorkImages: [
        'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=400',
      ],
      pricingTable: [
        {'item': 'Trip switch fault check', 'price': 1500.0, 'unit': 'inspection'},
        {'item': 'Ceiling fan install', 'price': 2200.0, 'unit': 'per fan'},
        {'item': 'New power point wiring', 'price': 2800.0, 'unit': 'per point'},
      ],
    ),
  ];

  static List<Booking> initialBookings = [
    Booking(
      id: 'BK-092401',
      customerId: 'user_poornima',
      customerName: 'Poornima Madubashini',
      customerPhone: '077 123 4567',
      providerId: 'prov_kamal',
      providerName: 'Kamal Perera',
      serviceCategory: 'Plumbing',
      serviceItem: 'Pipe leak repair',
      bookingDate: DateTime.now().add(const Duration(days: 1)),
      timeSlot: '10:00 AM - 11:30 AM',
      totalPrice: 2500.0,
      depositAmount: 500.0,
      remainingAmount: 2000.0,
      status: 'confirmed',
      address: '5 Wallowa ST, Mickleham, VIC 3064',
      notes: 'Kitchen sink pipe is leaking underneath the counter.',
      createdAt: DateTime.now().subtract(const Duration(hours: 3)),
    ),
    Booking(
      id: 'BK-092388',
      customerId: 'user_poornima',
      customerName: 'Poornima Madubashini',
      customerPhone: '077 123 4567',
      providerId: 'prov_nadesha',
      providerName: 'Nadesha Silva',
      serviceCategory: 'Cleaning',
      serviceItem: 'Deep Kitchen Cleaning',
      bookingDate: DateTime.now().subtract(const Duration(days: 4)),
      timeSlot: '02:00 PM - 04:00 PM',
      totalPrice: 3500.0,
      depositAmount: 500.0,
      remainingAmount: 3000.0,
      status: 'completed',
      address: '5 Wallowa ST, Mickleham, VIC 3064',
      notes: 'Completed successfully.',
      createdAt: DateTime.now().subtract(const Duration(days: 5)),
    ),
  ];

  static List<Review> initialReviews = [
    Review(
      id: 'REV-101',
      bookingId: 'BK-092388',
      providerId: 'prov_nadesha',
      customerName: 'Poornima M.',
      rating: 5.0,
      comment: 'Very professional, arrived exactly on time and the kitchen was spotless! Pricing was completely upfront with no surprise costs.',
      tags: ['On time', 'Great work', 'Polite', 'Cleaned up'],
      createdAt: DateTime.now().subtract(const Duration(days: 4)),
    ),
    Review(
      id: 'REV-102',
      bookingId: 'BK-091992',
      providerId: 'prov_kamal',
      customerName: 'Rohan D.',
      rating: 5.0,
      comment: 'Fixed our leaking pipe quickly. Explained what caused it and gave a transparent quote before touching anything.',
      tags: ['Professional', 'Fast service', 'Fair price'],
      createdAt: DateTime.now().subtract(const Duration(days: 8)),
    ),
  ];

  static List<AppNotification> initialNotifications = [
    AppNotification(
      id: 'NOTIF-1',
      recipientId: 'prov_kamal',
      title: 'New Job Request received',
      message: 'Poornima booked Pipe leak repair for tomorrow 10:00 AM.',
      type: 'new_request',
      bookingId: 'BK-092401',
      timestamp: DateTime.now().subtract(const Duration(hours: 3)),
    ),
    AppNotification(
      id: 'NOTIF-2',
      recipientId: 'prov_kamal',
      title: 'Deposit Received (Rs. 500)',
      message: 'Initial deposit has been secured in escrow for BK-092401.',
      type: 'deposit_received',
      bookingId: 'BK-092401',
      timestamp: DateTime.now().subtract(const Duration(hours: 2)),
    ),
  ];
}
