// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrwe_i0U52r5Oggq8ESqkW9faq9nOnYXw',
    appId: '1:260910215659:web:3ff1ad2aa08b21d15829ae',
    messagingSenderId: '260910215659',
    projectId: 'fixit-home-knd-g05-4e8e6',
    authDomain: 'fixit-home-knd-g05-4e8e6.firebaseapp.com',
    storageBucket: 'fixit-home-knd-g05-4e8e6.firebasestorage.app',
    measurementId: 'G-PF96Z1CL8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS4QEpSwAPS4nP18iaSXwTJgT8C9VOiXE',
    appId: '1:260910215659:android:01fbae37c5e38bd75829ae',
    messagingSenderId: '260910215659',
    projectId: 'fixit-home-knd-g05-4e8e6',
    storageBucket: 'fixit-home-knd-g05-4e8e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrwe_i0U52r5Oggq8ESqkW9faq9nOnYXw',
    appId: '1:260910215659:ios:fd8e3bf882e82b485829ae',
    messagingSenderId: '260910215659',
    projectId: 'fixit-home-knd-g05-4e8e6',
    storageBucket: 'fixit-home-knd-g05-4e8e6.firebasestorage.app',
    iosBundleId: 'com.knd.hci.homeServiceBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrwe_i0U52r5Oggq8ESqkW9faq9nOnYXw',
    appId: '1:260910215659:ios:fd8e3bf882e82b485829ae',
    messagingSenderId: '260910215659',
    projectId: 'fixit-home-knd-g05-4e8e6',
    storageBucket: 'fixit-home-knd-g05-4e8e6.firebasestorage.app',
    iosBundleId: 'com.knd.hci.homeServiceBookingApp',
  );
}
